Add `$vr-border-width` to _variables.scss
`$vr-border-width` was introduced in Bootstrap [v5.3.1](https://github.com/twbs/bootstrap/releases/tag/v5.3.1) via https://github.com/twbs/bootstrap/commit/6a9b9af59e0e279e3fc6eb46a043f9a4eae578fe.

Without this variable, Hugo throws the following error during build:

```sh
Error: error building site: TOCSS: failed to transform "scss/app.scss" (text/x-scss): "./node_modules/bootstrap/scss/helpers/_vr.scss:4:10": Undefined variable: "$vr-border-width".
```